// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBcW_NS_2_TLzWj8OV8YEVc7pEmxmwQ5s',
    appId: '1:307020637467:web:94889a3fa0fbf5fa28dfbe',
    messagingSenderId: '307020637467',
    projectId: 'pegas-pos',
    authDomain: 'pegas-pos.firebaseapp.com',
    storageBucket: 'pegas-pos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOhro_BA1QqHGQL3o6lQ1Nlp5LptX3bLk',
    appId: '1:307020637467:android:d884d9a8b99a8c3e28dfbe',
    messagingSenderId: '307020637467',
    projectId: 'pegas-pos',
    storageBucket: 'pegas-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqUTwrp7VimdCh2lqPovpY3geKOmT5Sck',
    appId: '1:307020637467:ios:faeb7158e0abad3d28dfbe',
    messagingSenderId: '307020637467',
    projectId: 'pegas-pos',
    storageBucket: 'pegas-pos.firebasestorage.app',
    iosBundleId: 'com.example.posApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqUTwrp7VimdCh2lqPovpY3geKOmT5Sck',
    appId: '1:307020637467:ios:faeb7158e0abad3d28dfbe',
    messagingSenderId: '307020637467',
    projectId: 'pegas-pos',
    storageBucket: 'pegas-pos.firebasestorage.app',
    iosBundleId: 'com.example.posApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBcW_NS_2_TLzWj8OV8YEVc7pEmxmwQ5s',
    appId: '1:307020637467:web:25f4ee879ed817b228dfbe',
    messagingSenderId: '307020637467',
    projectId: 'pegas-pos',
    authDomain: 'pegas-pos.firebaseapp.com',
    storageBucket: 'pegas-pos.firebasestorage.app',
  );

}